[package]
name = "apachi_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apachi_shared = { path = "../apachi_shared" }
rand = "0.8.5"
